#line 2 "scanner.c"

#line 4 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[251] =
    {   0,
        0,    0,   94,   92,   35,   36,   37,   34,   64,   92,
       56,   43,   92,   49,   50,   44,   53,   40,   54,   42,
       55,   84,   84,   52,   41,   68,   38,   67,   51,   92,
       83,   47,   48,   74,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   45,
       75,   46,   73,   70,    0,   87,   63,   65,   78,    0,
        0,   61,   57,   59,   58,   60,   39,    0,    0,   91,
       62,    0,   84,   84,    0,   76,   72,   69,   71,   77,
        0,   88,   83,   80,   83,   83,   83,   83,   83,   83,
        8,   83,   83,   83,   83,   83,   83,   17,   83,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   79,
       66,   85,    0,   85,    0,    0,    0,    0,   10,    0,
        0,   91,   86,   84,   81,   82,   89,   90,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   15,
       83,   18,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,    0,    0,    0,
        0,    0,   91,    1,   83,    3,    4,   83,   83,   83,
       83,   11,   12,   83,   83,   16,   19,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   31,   83,
       83,    0,    0,    0,   85,    0,    0,    2,    5,   83,

       83,   83,   83,   14,   83,   83,   22,   83,   83,   83,
       83,   83,   83,   29,   83,   83,   33,    0,    0,   83,
       83,    9,   13,   83,   21,   23,   24,   25,   26,   27,
       83,   83,   83,    0,    0,   83,    7,   83,   28,   83,
       83,    0,    6,   20,   30,   32,    0,    0,    0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   29,   29,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   31,   30,   30,   30,   30,   30,
       32,   33,   34,   35,    1,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   30,   45,   46,   47,   48,
       49,   50,   30,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    1,    4,    5,
        5,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[273] =
    {   0,
        0,    0,  325,  326,  326,  326,  326,  326,  299,  316,
      297,   55,  288,  326,  326,  295,   51,  326,   52,  302,
       54,   54,   64,  326,  326,   45,  293,   61,  326,   38,
        0,  326,  326,  292,  262,  264,   46,   51,   46,   47,
      265,   56,  264,  272,   62,  253,  262,  260,  265,  326,
       41,  326,  326,  326,  300,  299,  326,  326,  326,  295,
       88,  326,  326,  326,  326,  326,  326,  287,  290,    0,
      326,   93,  103,  108,    0,  277,  326,  326,  326,  276,
       85,  326,    0,  326,  247,  259,  246,  261,  248,  254,
      240,  241,  238,  238,  241,  238,  235,    0,  234,  238,

       68,  236,   67,   80,  240,  233,   86,   88,  238,  326,
      326,  326,  271,  270,  127,  269,  268,  267,  326,  263,
      122,    0,  129,    0,  326,  326,  326,  326,  226,  238,
      233,  221,   91,  235,  233,  229,  221,  227,  230,    0,
      216,    0,  222,  219,  208,  210,  212,  219,  205,  203,
      203,  215,  205,  209,  213,  215,  204,  132,    0,    0,
      239,  235,  326,    0,  202,    0,    0,  193,  201,  190,
      197,    0,    0,  191,  188,    0,    0,  188,  188,  185,
      197,  187,  191,  196,  195,  193,  183,  188,    0,  176,
      188,  217,    0,    0,  326,  213,  123,    0,    0,  177,

      178,  183,  174,    0,  168,  172,    0,  180,  177,  179,
      163,  172,  174,    0,  165,  168,    0,    0,    0,  157,
      157,    0,    0,  169,    0,    0,    0,    0,    0,    0,
      167,  167,  160,    0,  195,  164,    0,  152,    0,  163,
      161,    0,    0,    0,    0,    0,    0,    0,  190,  326,
      152,  157,  159,  164,  169,  174,  195,  177,  179,  181,
      185,  194,  193,  190,  192,  172,  162,  155,  150,  135,
      129,  113
    } ;

static yyconst flex_int16_t yy_def[273] =
    {   0,
      250,    1,  250,  250,  250,  250,  250,  250,  250,  251,
      250,  250,  252,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      253,  250,  250,  250,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  250,
      250,  250,  250,  250,  251,  251,  250,  250,  250,  250,
      254,  250,  250,  250,  250,  250,  250,  250,  255,  256,
      250,  250,  250,  250,  257,  250,  250,  250,  250,  250,
      250,  250,  253,  250,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  250,
      250,  250,  250,  250,  250,  258,  259,  260,  250,  255,
      261,  256,  250,  257,  250,  250,  250,  250,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  250,  262,  263,
      260,  264,  250,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  250,  265,  266,  250,  264,  261,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  267,  268,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  269,  250,  253,  253,  253,  253,  253,
      253,  270,  253,  253,  253,  253,  271,  272,  250,    0,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250
    } ;

static yyconst flex_uint16_t yy_nxt[390] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   31,
       31,   32,    4,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   31,   42,   31,   43,   31,   31,   31,   31,
       44,   45,   46,   47,   48,   49,   31,   31,   31,   50,
       51,   52,   53,   58,   63,  110,   69,   65,   76,   77,
       72,   70,   73,   73,   74,   64,   66,   67,   71,   59,
       72,   87,   74,   74,   74,   79,   80,   81,   88,   82,
       90,   92,   95,   93,   89,   96,   98,  114,  127,   91,

      128,  111,   94,   99,  102,  103,  115,  115,  147,  144,
       75,  123,  123,  123,  104,  149,  249,  105,  116,   72,
      145,   73,   73,   74,   72,  148,   74,   74,   74,  153,
      150,  155,  248,  156,  121,  197,  112,  154,  247,  163,
      163,  117,  168,  169,  118,  158,  158,  123,  123,  123,
      192,  192,   55,  242,   55,   55,   55,   60,  235,   60,
       60,   60,   83,   83,  113,  234,  113,  113,  113,  120,
      120,  120,  120,  120,  122,  219,  122,  122,  122,  159,
      159,  160,  160,  161,  161,  162,  162,  162,  162,  162,
      196,  196,  196,  196,  196,  218,  194,  193,  124,  195,

      246,  245,  244,  243,  195,  241,  240,  239,  238,  237,
      236,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  197,  112,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  195,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  167,  166,  165,  164,  121,  112,  112,  112,  112,
      112,  157,  152,  151,  146,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  133,  132,  131,  130,  129,

      126,  125,  121,  119,  112,   56,   56,  109,  108,  107,
      106,  101,  100,   97,   86,   85,   84,   78,   68,   62,
       61,   57,   56,   54,  250,    3,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250
    } ;

static yyconst flex_int16_t yy_chk[390] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   12,   17,   51,   21,   19,   26,   26,
       22,   21,   22,   22,   22,   17,   19,   19,   21,   12,
       23,   37,   23,   23,   23,   28,   28,   30,   37,   30,
       38,   39,   40,   39,   37,   40,   42,   61,   81,   38,

       81,   51,   39,   42,   45,   45,   61,   61,  103,  101,
       22,   72,   72,   72,   45,  104,  272,   45,   61,   73,
      101,   73,   73,   73,   74,  103,   74,   74,   74,  107,
      104,  108,  271,  108,  121,  197,  115,  107,  270,  121,
      197,   61,  133,  133,   61,  115,  115,  123,  123,  123,
      158,  158,  251,  269,  251,  251,  251,  252,  268,  252,
      252,  252,  253,  253,  254,  267,  254,  254,  254,  255,
      255,  255,  255,  255,  256,  266,  256,  256,  256,  258,
      258,  259,  259,  260,  260,  261,  261,  261,  261,  261,
      264,  264,  264,  264,  264,  265,  263,  262,  257,  249,

      241,  240,  238,  236,  235,  233,  232,  231,  224,  221,
      220,  216,  215,  213,  212,  211,  210,  209,  208,  206,
      205,  203,  202,  201,  200,  196,  192,  191,  190,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      175,  174,  171,  170,  169,  168,  165,  162,  161,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  141,  139,  138,  137,  136,  135,
      134,  132,  131,  130,  129,  120,  118,  117,  116,  114,
      113,  109,  106,  105,  102,  100,   99,   97,   96,   95,
       94,   93,   92,   91,   90,   89,   88,   87,   86,   85,

       80,   76,   69,   68,   60,   56,   55,   49,   48,   47,
       46,   44,   43,   41,   36,   35,   34,   27,   20,   16,
       13,   11,   10,    9,    3,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
#include <iostream>
#include <fstream>
#include <sstream>
#include <cstdio>
#include <cstring>
#include "parser.h"
#include "SymbolTable.h"
#include "SymbolNode.h"

using namespace std;

//Global for the @p++ and @p-- toggle.
extern bool outputProductions;

//Globals to hold line, columns, and tab.
int line = 1;
int column = 1;
int tab = 0;
//External bools to hook in with the command line arguments parsed in the yacc file.
extern bool command_l;
extern bool command_s;

//External streams for the final output and error
extern stringstream outputStream;
extern stringstream errorStream;

//External variable for the symbol table
extern SymbolTable st;
extern string lastNodeInserted;

//Functions to handle incrementing of globals.
/*
 *@name handleNewLine
 *@brief Keeps track of line, column, and tabs when a new line character is found
*/
void handleNewline();

/*
 *@name incrementColum
 *@brief increments the global column based on the int input
 *@param an integer n representing how many columns to increment
*/
void incrementColumn(int n);

/*
 *@name incrementTab
 *@brief increments the global tab based on the int input
 *@param an integer n representing how many tabs to increment
*/
void incrementTab(int n);

/*
 *@name scannerOutput
 *@brief Outputs the token name and source code to the lexDebugOutput output stream
 *@param a string outputStr that holds the source code to output
 *@param a string token_name that holds the token name to output
*/
void scannerOutput(string s, string token_name);

#line 701 "scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 97 "scanner.l"


#line 922 "scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 251 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 326 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 99 "scanner.l"
{                            
                            scannerOutput(yytext, "AUTO");
							incrementColumn(yyleng);
                            return AUTO;
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "scanner.l"
{
                            scannerOutput(yytext, "BREAK");
							incrementColumn(yyleng);
                            return BREAK;
                        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 111 "scanner.l"
{
                            scannerOutput(yytext, "CASE");
							incrementColumn(yyleng);
                            return CASE;
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 117 "scanner.l"
{
                            scannerOutput(yytext, "CHAR");
							incrementColumn(yyleng);
                            return CHAR;
                        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 123 "scanner.l"
{
                            scannerOutput(yytext, "CONST");
							incrementColumn(yyleng);
                            return CONST;
                        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 129 "scanner.l"
{
                            scannerOutput(yytext, "CONTINUE");
							incrementColumn(yyleng);
                            return CONTINUE;
                        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 135 "scanner.l"
{
                            scannerOutput(yytext, "DEFAULT");
							incrementColumn(yyleng);
                            return DEFAULT;
                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 141 "scanner.l"
{
                            scannerOutput(yytext, "DO");
							incrementColumn(yyleng);
                            return DO;
                        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 147 "scanner.l"
{
                            scannerOutput(yytext, "DOUBLE");
							incrementColumn(yyleng);
                            return DOUBLE;
                        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 153 "scanner.l"
{
                            scannerOutput(yytext, "...");
							incrementColumn(yyleng);
                            return ELLIPSIS;
                        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 159 "scanner.l"
{
                            scannerOutput(yytext, "ELSE");
							incrementColumn(yyleng);
                            return ELSE;
                        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 165 "scanner.l"
{
                            scannerOutput(yytext, "ENUM");
							incrementColumn(yyleng);
                            return ENUM;
                        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 171 "scanner.l"
{
                            scannerOutput(yytext, "EXTERN");
							incrementColumn(yyleng);
                            return EXTERN;
                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 177 "scanner.l"
{
                            scannerOutput(yytext, "FLOAT");
							incrementColumn(yyleng);
                            return FLOAT;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 183 "scanner.l"
{
                            scannerOutput(yytext, "FOR");
							incrementColumn(yyleng);
                            return FOR;
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 189 "scanner.l"
{
                            scannerOutput(yytext, "GOTO");
							incrementColumn(yyleng);
                            return GOTO;
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 195 "scanner.l"
{
                            scannerOutput(yytext, "IF");
							incrementColumn(yyleng);
                            return IF;
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 201 "scanner.l"
{
                            scannerOutput(yytext, "INT");
							incrementColumn(yyleng);
                            return INT;
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 207 "scanner.l"
{
                            scannerOutput(yytext, "LONG");
							incrementColumn(yyleng);
                            return LONG;
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 213 "scanner.l"
{
                            scannerOutput(yytext, "REGISTER");
							incrementColumn(yyleng);
                            return REGISTER;
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 219 "scanner.l"
{
                            scannerOutput(yytext, "RETURN");
							incrementColumn(yyleng);
                            return RETURN;
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 225 "scanner.l"
{
                            scannerOutput(yytext, "SHORT");
							incrementColumn(yyleng);
                            return SHORT;
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 231 "scanner.l"
{
                            scannerOutput(yytext, "SIGNED");
							incrementColumn(yyleng);
                            return SIGNED;
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 237 "scanner.l"
{
                            scannerOutput(yytext, "SIZEOF");
							incrementColumn(yyleng);
                            return SIZEOF;
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 243 "scanner.l"
{
                            scannerOutput(yytext, "STATIC");
							incrementColumn(yyleng);
                            return STATIC;
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 249 "scanner.l"
{
                            scannerOutput(yytext, "STRUCT");
							incrementColumn(yyleng);
                            return STRUCT;
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 255 "scanner.l"
{
                            scannerOutput(yytext, "SWITCH");
							incrementColumn(yyleng);
                            return SWITCH;
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 261 "scanner.l"
{
                            scannerOutput(yytext, "TYPEDEF");
							incrementColumn(yyleng);
                            return TYPEDEF;
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 267 "scanner.l"
{
                            scannerOutput(yytext, "UNION");
							incrementColumn(yyleng);
                            return UNION;
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 273 "scanner.l"
{
                            scannerOutput(yytext, "UNSIGNED");
							incrementColumn(yyleng);
                            return UNSIGNED;
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 279 "scanner.l"
{
                            scannerOutput(yytext, "VOID");
							incrementColumn(yyleng);
                            return VOID;
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 285 "scanner.l"
{
                            scannerOutput(yytext, "VOLATILE");
							incrementColumn(yyleng);
                            return VOLATILE;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 291 "scanner.l"
{
                            scannerOutput(yytext, "WHILE");
							incrementColumn(yyleng);
                            return WHILE;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 297 "scanner.l"
{
							incrementColumn(yyleng);
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 301 "scanner.l"
{
                            incrementTab(1);
                        }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 305 "scanner.l"
{
                            handleNewline();
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 309 "scanner.l"
{
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 312 "scanner.l"
{
                            scannerOutput(yytext, "ASSIGN");
							incrementColumn(yyleng);
                            return ASSIGN;
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 318 "scanner.l"
{
                            scannerOutput(yytext, "ARROW");
							incrementColumn(yyleng);
                            return ARROW;
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 324 "scanner.l"
{
                            scannerOutput(yytext, "COMMA");
							incrementColumn(yyleng);
                            return COMMA;
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 330 "scanner.l"
{
                            scannerOutput(yytext, "SEMICOLON");
							incrementColumn(yyleng);
                            return SEMICOLON;
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 336 "scanner.l"
{
                            scannerOutput(yytext, "PERIOD");
							incrementColumn(yyleng);
                            return PERIOD;
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 342 "scanner.l"
{
                            scannerOutput(yytext, "AMPERSAND");
							incrementColumn(yyleng);
                            return AMPERSAND;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 348 "scanner.l"
{
                            scannerOutput(yytext, "STAR");
							incrementColumn(yyleng);
                            return STAR;
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 354 "scanner.l"
{
							
							if( command_s )
							{
								outputStream << st;
							}
                            scannerOutput(yytext, "OBRACE");
							incrementColumn(yyleng);
                            st.pushLevel();
							st.setInsertMode(false);
                            return OBRACE;
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 367 "scanner.l"
{
							if( command_s )
							{
								outputStream << st;
							}
                            scannerOutput(yytext, "CBRACE");
							incrementColumn(yyleng);
                            st.popLevel();
							st.setInsertMode(false);
                            return CBRACE;
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 379 "scanner.l"
{
                            scannerOutput(yytext, "OBRACKET");
							incrementColumn(yyleng);
                            return OBRACKET;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 385 "scanner.l"
{
                            scannerOutput(yytext, "CBRACKET");
							incrementColumn(yyleng);
                            return CBRACKET;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 391 "scanner.l"
{
                            scannerOutput(yytext, "OPAREN");
							incrementColumn(yyleng);
                            if (st.getInsertMode())
                            {
                                auto functionPair = st.searchTop(lastNodeInserted);

                                if (functionPair.first == -1)
                                {
                                    return ERROR;
                                }

                                functionPair.second->second.setIsFunction(true);
                                st.pushLevel();
                                cerr << st << endl;
                            }
                            return OPAREN;
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 410 "scanner.l"
{
                            scannerOutput(yytext, "CPAREN");
							incrementColumn(yyleng);
                            return CPAREN;
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 416 "scanner.l"
{
                            scannerOutput(yytext, "QUESTION");
							incrementColumn(yyleng);
                            return QUESTION;
                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 422 "scanner.l"
{
                            scannerOutput(yytext, "COLON");
							incrementColumn(yyleng);
                            return COLON;
                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 428 "scanner.l"
{
                            scannerOutput(yytext, "ADD");
							incrementColumn(yyleng);
                            return ADD;
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 434 "scanner.l"
{
                            scannerOutput(yytext, "SUB");
							incrementColumn(yyleng);
                            return SUB;
                        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 440 "scanner.l"
{
                            scannerOutput(yytext, "DIV");
							incrementColumn(yyleng);
                            return DIV;
                        }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 446 "scanner.l"
{
                            scannerOutput(yytext, "MOD");
							incrementColumn(yyleng);
                            return MOD;
                        }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 452 "scanner.l"
{
                            scannerOutput(yytext, "INC_OP");
							incrementColumn(yyleng);
                            return INC_OP;
                        }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 458 "scanner.l"
{
                            scannerOutput(yytext, "DEC_OP");
							incrementColumn(yyleng);
                            return DEC_OP;
                        }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 464 "scanner.l"
{
                            scannerOutput(yytext, "ADD_ASSIGN");
							incrementColumn(yyleng);
                            return ADD_ASSIGN;
                        }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 470 "scanner.l"
{
                            scannerOutput(yytext, "SUB_ASSIGN");
							incrementColumn(yyleng);
                            return SUB_ASSIGN;
                        }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 476 "scanner.l"
{
                            scannerOutput(yytext, "MUL_ASSIGN");
							incrementColumn(yyleng);
                            return MUL_ASSIGN;
                        }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 482 "scanner.l"
{
                            scannerOutput(yytext, "DIV_ASSIGN");
							incrementColumn(yyleng);
                            return DIV_ASSIGN;
                        }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 488 "scanner.l"
{
                            scannerOutput(yytext, "MOD_ASSIGN");
							incrementColumn(yyleng);
                            return MOD_ASSIGN;
                        }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 494 "scanner.l"
{
                            scannerOutput(yytext, "L_NOT");
							incrementColumn(yyleng);
                            return L_NOT;
                        }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 500 "scanner.l"
{
                            scannerOutput(yytext, "L_AND");
							incrementColumn(yyleng);
                            return L_AND;
                        }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 506 "scanner.l"
{
                            scannerOutput(yytext, "L_OR");
							incrementColumn(yyleng);
                            return L_OR;
                        }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 512 "scanner.l"
{
                            scannerOutput(yytext, "GT_OP");
							incrementColumn(yyleng);
                            return GT_OP;
                        }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 518 "scanner.l"
{
                            scannerOutput(yytext, "LT_OP");
							incrementColumn(yyleng);
                            return LT_OP;
                        }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 524 "scanner.l"
{
                            scannerOutput(yytext, "EQ_OP");
							incrementColumn(yyleng);
                            return EQ_OP;
                        }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 530 "scanner.l"
{
                            scannerOutput(yytext, "NE_OP");
							incrementColumn(yyleng);
                            return NE_OP;
                        }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 536 "scanner.l"
{
                            scannerOutput(yytext, "GE_OP");
							incrementColumn(yyleng);
                            return GE_OP;
                        }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 542 "scanner.l"
{
                            scannerOutput(yytext, "LE_OP");
							incrementColumn(yyleng);
                            return LE_OP;
                        }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 548 "scanner.l"
{
                            scannerOutput(yytext, "B_NOT");
							incrementColumn(yyleng);
                            return B_NOT;
                        }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 554 "scanner.l"
{
                            scannerOutput(yytext, "B_XOR");
							incrementColumn(yyleng);
                            return B_XOR;
                        }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 560 "scanner.l"
{
                            scannerOutput(yytext, "B_OR");
							incrementColumn(yyleng);
                            return B_OR;
                        }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 566 "scanner.l"
{
                            scannerOutput(yytext, "B_SL");
							incrementColumn(yyleng);
                            return B_SL;
                        }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 572 "scanner.l"
{
                            scannerOutput(yytext, "B_SR");
							incrementColumn(yyleng);
                            return B_SR;
                        }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 578 "scanner.l"
{
                            scannerOutput(yytext, "B_AND_ASSIGN");
							incrementColumn(yyleng);
                            return B_AND_ASSIGN;
                        }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 584 "scanner.l"
{
                            scannerOutput(yytext, "B_OR_ASSIGN");
							incrementColumn(yyleng);
                            return B_OR_ASSIGN;
                        }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 590 "scanner.l"
{
                            scannerOutput(yytext, "B_XOR_ASSIGN");
							incrementColumn(yyleng);
                            return B_XOR_ASSIGN;
                        }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 596 "scanner.l"
{
                            scannerOutput(yytext, "B_SL_ASSIGN");
							incrementColumn(yyleng);
                            return B_SL_ASSIGN;
                        }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 602 "scanner.l"
{
                            scannerOutput(yytext, "B_SR_ASSIGN");
							incrementColumn(yyleng);
                            return B_SR_ASSIGN;
                        }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 608 "scanner.l"
{
							if( yyleng > 253 )
							{
								return ERROR;//ID too long
							}
                            scannerOutput(yytext, "IDENTIFIER");
							incrementColumn(yyleng);
                            strcpy(yylval.sval, yytext);
                            return IDENTIFIER;
                        }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 619 "scanner.l"
{
                            scannerOutput(yytext, "INTEGER_CONSTANT");
							if( yyleng > 10 or (yyleng == 10 and strcmp(yytext, "2147483647") > 0) )
							{
								
								errorStream << "WARNING: Integer " << yytext << " too big to be held in an int" << endl;
							}
							incrementColumn(yyleng);
                            strcpy(yylval.sval, yytext);
                            return INTEGER_CONSTANT;
                        }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 631 "scanner.l"
{
                            scannerOutput(yytext, "CHARACTER_CONSTANT");
							incrementColumn(yyleng);
                            strcpy(yylval.sval, yytext);
                            return CHARACTER_CONSTANT;
                        }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 638 "scanner.l"
{
							try//Test to check if yytext is a valid float.
							{
								stof(yytext);
							}
							catch(...)
							{
								errorStream << "WARNING: float " << yytext << " too big to be held in an float" << endl;
							}
							
                            scannerOutput(yytext, "FLOATING_CONSTANT");
							incrementColumn(yyleng);
                            strcpy(yylval.sval, yytext);
                            return FLOATING_CONSTANT;
                        }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 654 "scanner.l"
{
                            scannerOutput(yytext, "STRING_LITERAL");
							incrementColumn(yyleng);
                            strcpy(yylval.sval, yytext);
                            return STRING_LITERAL;
                        }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 661 "scanner.l"
{
							scannerOutput(yytext, "SYMBOL_TABLE_DUMP");
							incrementColumn(yyleng);
                            outputStream << st;
						}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 667 "scanner.l"
{
                            outputProductions = true;
                        }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 671 "scanner.l"
{
                            outputProductions = false;
                        }
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 675 "scanner.l"
{
							scannerOutput(yytext, "COMMENT");
						}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 679 "scanner.l"
{
                            scannerOutput(yytext, "ERROR");
							//incrementColumn(yyleng); //Want the error to point to the start of the error.
                            strcpy(yylval.sval, yytext);
                            return ERROR;
                        }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 686 "scanner.l"
ECHO;
	YY_BREAK
#line 1849 "scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 251 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 251 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 250);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 686 "scanner.l"




/*
 *@name handleNewLine
 *@brief Keeps track of line, column, and tabs when a new line character is found
*/
inline void handleNewline()
{
    line++;
    column = 1;
    tab = 0;
}

/*
 *@name incrementColum
 *@brief increments the global column based on the int input
 *@param an integer n representing how many columns to increment
*/
inline void incrementColumn(int n)
{
    column += n;
}

/*
 *@name incrementTab
 *@brief increments the global tab based on the int input
 *@param an integer n representing how many tabs to increment
*/
inline void incrementTab(int n)
{
    tab += n;
}

/*
 *@name scannerOutput
 *@brief Outputs the token name and source code to the lexDebugOutput output stream
 *@param a string outputStr that holds the source code to output
 *@param a string token_name that holds the token name to output
*/
void scannerOutput(string outputStr, string token_name)
{
	if( command_l )
	{
    	outputStream << "Token: " << token_name << endl << "\tSource: " << outputStr << endl;
	}
}

